# Site settings
title: Steven's Blog
email: stevenjlho@gmail.com
description: 记录我的学习心得
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.studyby.me" # the base hostname & protocol for your site
twitter_username: stevenjlho
github_username: stevenjlho

# Build settings
markdown: kramdown
kramdown:
  input: GFM
